<?php

namespace App\Enums;

enum ActionReport: string
{
    case DISPOSITION_REPORT = 'DISPOSITION_REPORT';
    case VERIFY_INITIAL = 'VERIFY_INITIAL';
    case REQUEST_FURTHER_REVIEW = 'REQUEST_FURTHER_REVIEW';
    case APPROVE_DISTRICT = 'APPROVE_DISTRICT';
    case REJECT_DISTRICT = 'REJECT_DISTRICT';
    case ASSIGN_FIELD_OFFICER = 'ASSIGN_FIELD_OFFICER';
    case SUBMIT_FIELD_RESULT = 'SUBMIT_FIELD_RESULT';
    case VERIFY_RESULT = 'VERIFY_RESULT';
    case REQUEST_REVISION = 'REQUEST_REVISION';
    case COMPLETE_REPORT = 'COMPLETE_REPORT';

}
